### ISSUE TITLE
Dyno Client with Redis Sentinel setup 

### ISSUE THREAD

**Issue by manjurad** [Netflix/dyno#189]
I want to use Netflix/Conductor service which makes uses of Netflix/Dyno Client to talk to Redis instance. I would like to use a Redis Sentinel pool for HA purposes, and wondering if there are plans or has anyone managed to get Dyno to work with pool of hosts that are running Sentinel+Redis ?

**Comment by ipapapa** [comment]
I think Conductor allows you to use the vanilla Jedis if you are not interested in Dynomite.

**Comment by manjurad** [comment]
@ipapapa I am open to using Dynomite but I am not sure what services are needed to make it work correctly for High availability. I opened the following issue https://github.com/Netflix/conductor/issues/354 since by the face of it looks like I must use Dynomite Manager + Cassandra and Eureka for Dynomite to work correctly in case of Redis failure (while Dynomite on the same node is fine), node failure (Redis and Dynomite is down) etc. 

Would you be able to clarify what is the minimum set of services I need to get Netflix/Conductor to use Dynomite Cluster with High availability?

**Comment by ipapapa** [comment]
Dynomite is a C proxy that does not need Dynomite Manager. Many folks have done their own implementations. This is one good example: https://github.com/Smile-SA/dagota or in another case Dynomite manager was modified to support ECS: https://github.com/VideoAmp/dynomite-manager/tree/feature/ecs_support In some other cases, people have integrated the token topology description inside the client application. We would love though to see Dynomite Manager to be extended in order to support multiple environments and token databases, but there are multiple options available. We just provided a paved path that has worked for us and several other companies for several years now.

**Comment by v1r3n** [comment]
You can use Conductor with a redis server without dynomite.  specify `db=redis` in the configuration.  
Look at the https://netflix.github.io/conductor/server/#configuration-parameters for the details.

**Comment by ipapapa** [comment]
It seems that this issue is idle for a few days. I assume the question has been answered therefore I am closing this. We can reopen it or open a new one for further clarifications.
